### ISSUE TITLE
Customizing from the blog

### ISSUE THREAD

**Issue by Smarciz** [samuelguebo/acajou#1]
Hi, 

First - I love this theme for wordpress. I have been struggling to find one that I like.  I love how clean and the simple elegance of it.  So, thank you for it!

I do have one thing I can't figure out how to do without an error. Customizing the 'from the blog' text gives me an error no matter what format I try: character types, length, etc.  

![wpblthm](https://cloud.githubusercontent.com/assets/29220489/26813713/0362b252-4a4e-11e7-90a7-9331ea952507.PNG)

Is there a certain format it must follow, or is this a bug?

**Comment by samuelguebo** [comment]
Hello @Smarciz and thank you for poking me about this issue. It is actually a bug related to how the text from the input field was sanitized. I am fixing it now and updating the theme. I really appreciated your help.

**Comment by Smarciz** [comment]
WOW! Thank you so much! I really appreciate you fixing that and will download the fix as I LOVE this theme.. thank you!

**Comment by Smarciz** [comment]
Works beautifully!  Thanks again!

**Comment by samuelguebo** [comment]
You're welcome!
